submodules = [
    [
    'repos/rust',
    'src/doc/book',
],
    [
    'repos/rust',
    'src/tools/cargo',
],
    [
    'repos/rust',
    'src/doc/edition-guide',
],
    [
    'repos/rust',
    'src/doc/embedded-book',
],
    [
    'repos/rust',
    'src/doc/nomicon',
],
    [
    'repos/rust',
    'src/doc/reference',
],
    ['repos/rust-cli'],
]
[books.book]
path = 'repos/rust/src/doc/book'

[[books.book.translations]]
id = 'ja'
name = '日本語'

[[books.book.translations]]
id = 'ru'
name = 'Русский'

[[books.book.translations]]
id = 'ko'
name = '한국어'

[books.cargo]
path = 'repos/rust/src/tools/cargo/src/doc'

[[books.cargo.translations]]
id = 'ja'
name = '日本語'

[[books.cargo.translations]]
id = 'ko'
name = '한국어'

[books.edition-guide]
path = 'repos/rust/src/doc/edition-guide'

[[books.edition-guide.translations]]
id = 'ko'
name = '한국어'

[books.embedded-book]
path = 'repos/rust/src/doc/embedded-book'

[[books.embedded-book.translations]]
id = 'ko'
name = '한국어'

[books.nomicon]
path = 'repos/rust/src/doc/nomicon'

[[books.nomicon.translations]]
id = 'ko'
name = '한국어'

[books.reference]
path = 'repos/rust/src/doc/reference'

[[books.reference.translations]]
id = 'ko'
name = '한국어'

[books.rust-cli]
path = 'repos/rust-cli'

[[books.rust-cli.translations]]
id = 'ko'
name = '한국어'

[books.rustc]
path = 'repos/rust/src/doc/rustc'
translations = []

[books.rustdoc]
path = 'repos/rust/src/doc/rustdoc'
translations = []
