name: Regression

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: beta
      - uses: Swatinem/rust-cache@v2
      - name: Build document
        run: |
          cargo run --release -- build
